<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <ApplicationIcon>wwwroot\assets\favicon.ico</ApplicationIcon>
    <UserSecretsId>3c2253ee-d436-40f1-8618-bd1ada91e82d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="logs\**" />
    <Compile Remove="wwwroot\uploads\**" />
    <Content Remove="logs\**" />
    <Content Remove="wwwroot\uploads\**" />
    <EmbeddedResource Remove="logs\**" />
    <EmbeddedResource Remove="wwwroot\uploads\**" />
    <None Remove="logs\**" />
    <None Remove="wwwroot\uploads\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.MySql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.MySql.Storage" Version="9.0.0" />
    <PackageReference Include="Duende.IdentityModel" Version="8.1.0" />
    <PackageReference Include="IdentityModel" Version="5.2.0" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bedrock.Configuration\Bedrock.Configuration.csproj" />
    <ProjectReference Include="..\Bedrock.Infrastructure\Bedrock.Infrastructure.csproj" />
    <ProjectReference Include="..\Bedrock.Application\Bedrock.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>
</Project>
